name: Feature request
description: Suggest an improvement to BODS Bus Tracker
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: What problem would this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behaviour
      description: Describe how you would like the integration to behave.
    validations:
      required: true
